[package]
name = "animality"
version = "1.0.0"
edition = "2021"
description = "API wrapper for the https://animality.xyz api"
license_file = "LICENSE"
keywords = ["animals", "api", "api-wrapper", "web"]
repository = "https://github.com/animality-xyz/animality.rs"
readme = "README.md"

[dependencies]
native-tls = "0.2.10"
serde_json = { version = "1.0.81", features = [], default-features = false }